import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {createCharacter} from './character';
import {presets,normalizeAppearance} from '../shared/appearance.mjs';
import type {Appearance} from './appearance';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
export function useAppearance(){const [character,setCharacter]=useState(0),[appearance,setAppearance]=useState<Appearance>(()=>normalizeAppearance(undefined,0));
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('office-bluff-look')??'null');if(saved&&Number.isInteger(saved.character)&&saved.character>=0&&saved.character<4){setCharacter(saved.character);setAppearance(normalizeAppearance(saved.appearance,saved.character));}}catch{}},[]);
 const save=(c:number,a:Appearance)=>{setCharacter(c);setAppearance(a);try{localStorage.setItem('office-bluff-look',JSON.stringify({character:c,appearance:a}))}catch{}};
 return {character,appearance,choose:(c:number)=>save(c,normalizeAppearance(undefined,c)),change:(a:Appearance)=>save(character,normalizeAppearance(a,character))};
}
export function CharacterEditor({character,appearance,onChoose,onChange}:{character:number;appearance:Appearance;onChoose:(i:number)=>void;onChange:(a:Appearance)=>void}){
 const [custom,setCustom]=useState(false);
 return <div className="character-editor"><div className="hand-label">4 GƯƠNG MẶT QUEN</div><div className="preset-grid">{presets.map((p,i)=><button type="button" key={p.name} aria-pressed={character===i} className={character===i?'selected-preset':''} onClick={()=>onChoose(i)}><span className="preset-number">0{i+1}</span><strong>{p.name}</strong><small>{p.role}</small></button>)}</div><button className="custom-toggle" type="button" aria-expanded={custom} onClick={()=>setCustom(!custom)}>{custom?'Đóng chỉnh sửa':'✦ Tùy chỉnh diện mạo'} <span>{custom?'−':'+'}</span></button>{custom&&<div className="custom-fields"><p>Chỉnh trực tiếp trên nhân vật bên cạnh. Lựa chọn được lưu trên máy này.</p><div className="color-fields">{([['shirt','Màu áo'],['pants','Màu quần'],['skin','Màu da'],['hair','Màu tóc'],['shoes','Giày / dép']] as const).map(([key,label])=><label key={key}>{label}<input aria-label={label} type="color" value={appearance[key]} onChange={e=>onChange({...appearance,[key]:e.target.value})}/></label>)}</div>{([{key:'hairStyle',label:'Kiểu tóc',choices:[['parted','Rẽ ngôi'],['short','Tóc ngắn'],['swept','Vuốt lệch'],['fringe','Tóc mái'],['bald','Hói']]},{key:'pantsStyle',label:'Kiểu quần',choices:[['shorts','Quần short'],['long','Quần dài']]},{key:'glasses',label:'Kính',choices:[['none','Không kính'],['clear','Gọng kính'],['sun','Kính râm']]},{key:'outfit',label:'Trang phục',choices:[['jersey','Áo thể thao 11'],['graphic','Áo thun BALI'],['polo','Áo polo'],['striped','Sơ mi sọc']]}] as const).map(field=><div className="editor-select" key={field.key}><span id={`label-${field.key}`}>{field.label}</span><Select value={appearance[field.key]} onValueChange={v=>{if(v)onChange({...appearance,[field.key]:v})}}><SelectTrigger aria-labelledby={`label-${field.key}`}><SelectValue>{field.choices.find(c=>c[0]===appearance[field.key])?.[1]}</SelectValue></SelectTrigger><SelectContent>{field.choices.map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div>)}<label className="build-field">Dáng người <span>{Math.round(appearance.build*100)}%</span><input type="range" min="85" max="120" value={Math.round(appearance.build*100)} onChange={e=>onChange({...appearance,build:Number(e.target.value)/100})}/></label><button type="button" className="back-button" onClick={()=>onChoose(character)}>Khôi phục mẫu {presets[character].name}</button></div>}</div>;
}
export function CharacterPreview({character,appearance,reset=0}:{character:number;appearance:Appearance;reset?:number}){
 const host=useRef<HTMLDivElement>(null);const [failed,setFailed]=useState(false);
 useEffect(()=>{const el=host.current;if(!el)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true})}catch{setFailed(true);return}setFailed(false);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor('#12252d');renderer.toneMapping=THREE.ACESFilmicToneMapping;el.appendChild(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(33,1,.1,40);camera.position.set(0,2.4,6.7);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1.55,0);controls.enablePan=false;controls.minDistance=4;controls.maxDistance=9;controls.maxPolarAngle=Math.PI*.55;controls.enableDamping=true;
 const rig=createCharacter(appearance.shirt,character,appearance);scene.add(rig.root);scene.add(new THREE.HemisphereLight('#e1f5ff','#463626',3));const light=new THREE.DirectionalLight('#ffe4bd',4);light.position.set(3,5,4);scene.add(light);const fill=new THREE.DirectionalLight('#81cde4',2);fill.position.set(-3,2,-2);scene.add(fill);
 const geo=new THREE.CylinderGeometry(1.05,1.16,.16,64),mat=new THREE.MeshStandardMaterial({color:'#304b50',metalness:.4,roughness:.6}),platform=new THREE.Mesh(geo,mat);platform.position.y=.32;scene.add(platform);
 const resize=()=>{renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix()};const ro=new ResizeObserver(resize);ro.observe(el);resize();const start=performance.now();const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let frame=0;const draw=()=>{rig.update((performance.now()-start)/1000,null,false,reduced);controls.update();renderer.render(scene,camera);frame=requestAnimationFrame(draw)};draw();return()=>{cancelAnimationFrame(frame);ro.disconnect();controls.dispose();rig.dispose();geo.dispose();mat.dispose();renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove()};
 },[character,JSON.stringify(appearance),reset]);
 return <div className="character-preview" ref={host} aria-label={`Xem trước nhân vật ${presets[character].name}`}>{failed&&<p>Không thể mở 3D. Hãy bật tăng tốc phần cứng của trình duyệt.</p>}<div className="preview-caption"><span>NHÂN VẬT CỦA BẠN</span><strong>{presets[character].name}</strong><small>Kéo để xoay · Cuộn để thu phóng</small></div></div>;
}
