'use client';
import {useEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import * as THREE from 'three';
import {createCharacter} from './character';
import {createCardMotion,type TableCards} from './card-motion';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {HelpCircle,RotateCcw,ArrowUpRight,Volume2,VolumeX,Club,ChevronRight} from 'lucide-react';
export const people=[{name:'Minh',role:'Team công nghệ',color:'#e4aa55',quote:'“Máy em vẫn chạy mà.”'},{name:'Linh',role:'Team sáng tạo',color:'#ae8acb',quote:'“Một chỉnh sửa nhỏ thôi.”'},{name:'Huy',role:'Team kinh doanh',color:'#62b4a6',quote:'“Chốt kèo này nhé.”'},{name:'An',role:'Team nhân sự',color:'#e07c68',quote:'“Mình nói chuyện chút nha.”'}];
type Card='K'|'Q'|'A'|'★';
type Game={hands:Card[][];turn:number;last:null|{who:number;cards:Card[]};lives:number[];target:Card;round:number;log:string[];phase:'play'|'result'|'end';result:string;loser:number;winner:number};
function deal():Card[][]{const deck:Card[]=[...Array(6).fill('K'),...Array(6).fill('Q'),...Array(6).fill('A'),'★','★'];for(let i=deck.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]];}return [0,1,2,3].map(i=>deck.slice(i*5,i*5+5));}
function fresh():Game{return {hands:deal(),turn:0,last:null,lives:[3,3,3,3],target:['K','Q','A'][Math.floor(Math.random()*3)] as Card,round:1,log:['Bàn đã sẵn sàng. Bạn đi trước!'],phase:'play',result:'',loser:-1,winner:-1};}
function nextPlayer(g:Game,from:number){for(let n=1;n<4;n++){const k=(from+n)%4;if(g.lives[k]>0&&g.hands[k].length)return k;}for(let n=1;n<4;n++){const k=(from+n)%4;if(g.lives[k]>0)return k;}return from;}
function challenge(g:Game,caller:number,names:string[]):Game{if(!g.last)return g;const lied=g.last.cards.some(c=>c!==g.target&&c!=='★');const loser=lied?g.last.who:caller;const lives=g.lives.map((n,i)=>i===loser?n-1:n);const alive=lives.map((n,i)=>n>0?i:-1).filter(i=>i>=0);const result=`${names[g.last.who]} ${lied?'đã nói dối':'nói thật'}! ${names[loser]} mất 1 cà phê. Bài lật: ${g.last.cards.join(' · ')}.`;return {...g,lives,loser,phase:alive.length===1?'end':'result',winner:alive.length===1?alive[0]:-1,result,log:[result,...g.log].slice(0,8)};}
function playCards(g:Game,ids:number[],names:string[]):Game{const who=g.turn;const cards=g.hands[who].filter((_,i)=>ids.includes(i));if(!cards.length||cards.length>3)return g;const hands=g.hands.map((h,i)=>i===who?h.filter((_,j)=>!ids.includes(j)):h);const after={...g,hands,last:{who,cards},log:[`${names[who]} đánh ${cards.length} lá ${g.target}.`,...g.log].slice(0,8)};return {...after,turn:nextPlayer(after,who)};}
export function Room({chosen,turn,loser,reset,characters,cards,accusation}:{chosen:number;turn:number;loser:number;reset:number;characters?:number[];cards?:TableCards;accusation?:{from:number;to:number}}){
 const host=useRef<HTMLDivElement>(null);const live=useRef({turn,loser,cards,accusation,characters});live.current={turn,loser,cards,accusation,characters};const [error,setError]=useState(false);
 useEffect(()=>{if(!host.current)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});}catch{setError(true);return;}const el=host.current;renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.4;el.appendChild(renderer.domElement);
 const scene=new THREE.Scene();scene.background=new THREE.Color('#141b22');scene.fog=new THREE.Fog('#141b22',13,30);const camera=new THREE.PerspectiveCamera(40,1,.1,60);camera.position.set(7.8,7.7,10.8);const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,1.6,0);orbit.enableDamping=true;orbit.minDistance=8;orbit.maxDistance=17;orbit.maxPolarAngle=Math.PI/2.25;orbit.minPolarAngle=.3;orbit.enablePan=false;
 const materials:THREE.Material[]=[];function mat(c:string,metal=0){const m=new THREE.MeshStandardMaterial({color:c,roughness:.75,metalness:metal});materials.push(m);return m;}const wood=mat('#50332a'),darkWood=mat('#211e22'),felt=mat('#236058'),gold=mat('#c39953',.5),black=mat('#20212a'),skin=mat('#ecc0a0');
 function mesh(geo:THREE.BufferGeometry,m:THREE.Material,x:number,y:number,z:number,parent:THREE.Object3D=scene){const o=new THREE.Mesh(geo,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
 function box(w:number,h:number,d:number,m:THREE.Material,x:number,y:number,z:number,p:THREE.Object3D=scene){return mesh(new THREE.BoxGeometry(w,h,d),m,x,y,z,p);}function ball(r:number,m:THREE.Material,x:number,y:number,z:number,p:THREE.Object3D=scene){return mesh(new THREE.SphereGeometry(r,20,16),m,x,y,z,p);}
 box(28,.15,28,mat('#27272a'),0,-.15,0);for(let x=-12;x<=12;x+=1.2)box(.025,.01,26,darkWood,x,-.065,0);box(24,9,.2,mat('#263038'),0,4,-6);for(let x=-10;x<11;x+=1.3)box(.055,5,.1,gold,x,2.5,-5.85);
 for(const x of [-6,6]){box(2.6,3.5,.18,darkWood,x,3,-5.65);box(2.3,3.2,.19,mat('#426674'),x,3,-5.53);box(.08,3.2,.2,gold,x,3,-5.4);box(2.3,.08,.2,gold,x,3,-5.4);}
 const table=mesh(new THREE.CylinderGeometry(3.05,3.05,.26,64),wood,0,1.6,0);table.scale.z=.8;const rim=mesh(new THREE.CylinderGeometry(2.88,2.88,.05,64),gold,0,1.75,0);rim.scale.z=.8;const top=mesh(new THREE.CylinderGeometry(2.81,2.81,.055,64),felt,0,1.79,0);top.scale.z=.8;box(.8,1.5,.8,darkWood,0,.7,0);
 const ring=mesh(new THREE.TorusGeometry(1.02,.012,8,80),gold,0,1.83,0);ring.rotation.x=-Math.PI/2;
 const positions=[[0,3.35],[-3.7,0],[0,-3.35],[3.7,0]];
 const rigs=positions.map(([x,z],i)=>{
   const variant=characters?.[i]??(chosen+i)%4;
   const rig=createCharacter(people[Math.max(0,variant)].color,Math.max(0,variant));
   const g=rig.root;scene.add(g);g.position.set(x,0,z);g.rotation.y=Math.atan2(-x,-z);
   box(1.2,.17,1.15,darkWood,0,.75,0,g);box(1.25,1.65,.18,wood,0,1.35,-.47,g);
   for(const a of [-.45,.45])for(const b of [-.4,.4])box(.11,.8,.11,black,a,.35,b,g);
   const mug=mesh(new THREE.CylinderGeometry(.12,.1,.24,16),mat('#e4cfaa'),x*.72,1.95,z*.65);
   const handle=mesh(new THREE.TorusGeometry(.08,.025,8,16),gold,x*.72+.12,1.95,z*.65); 
   return {...rig,mug,handle};
 });
 const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');
 const targetPoint=new THREE.Vector3();
 const cardMotion=createCardMotion(scene,positions);
 scene.add(new THREE.HemisphereLight('#aac8dc','#30201a',2));const light=new THREE.PointLight('#ffc382',110,18);light.position.set(0,6,0);light.castShadow=true;light.shadow.mapSize.set(1024,1024);scene.add(light);const fill=new THREE.DirectionalLight('#8dc8d6',2);fill.position.set(4,6,4);scene.add(fill);mesh(new THREE.ConeGeometry(1.3,.5,32,1,true),mat('#b58b48',.6),0,6.1,0);box(.035,4,.035,black,0,8,0);
 const marker=mesh(new THREE.TorusGeometry(.72,.035,8,48),gold,0,.04,0);marker.rotation.x=Math.PI/2;const resize=()=>{const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(el);resize();let frame=0;const start=performance.now();function draw(){const t=(performance.now()-start)/1000;cardMotion.update(live.current.cards,t);rigs.forEach((rig,i)=>{
   const roster=live.current.characters;
   rig.root.visible=roster===undefined||(i<roster.length&&roster[i]>=0);
   rig.mug.visible=rig.handle.visible=rig.root.visible;
   rig.root.position.y=reduced.matches?0:Math.sin(t*1.6+i)*.018;
   const accusation=live.current.accusation;
   let target:THREE.Vector3|null=null;
   if(accusation?.from===i&&rigs[accusation.to]?.root.visible){
     const [x,z]=positions[accusation.to];targetPoint.set(x,2.05,z);
     rig.root.updateMatrixWorld();target=rig.root.worldToLocal(targetPoint);
   }
   rig.update(t,target,!!live.current.cards?.counts[i],reduced.matches);
 });marker.visible=!!live.current.cards&&!!rigs[live.current.turn]?.root.visible;const pos=positions[live.current.turn]||positions[0];marker.position.set(pos[0],.02,pos[1]);orbit.update();renderer.render(scene,camera);frame=requestAnimationFrame(draw);}draw();return()=>{cancelAnimationFrame(frame);observer.disconnect();orbit.dispose();cardMotion.dispose();rigs.forEach(r=>{scene.remove(r.root);r.dispose();r.root.traverse(o=>{if(o instanceof THREE.Mesh)o.geometry.dispose();});});scene.traverse(o=>{if(o instanceof THREE.Mesh)o.geometry.dispose();});materials.forEach(m=>m.dispose());renderer.dispose();renderer.domElement.remove();};},[chosen,reset,characters?.join(",")]);
 return <div className="room" ref={host} aria-label={`Bàn chơi 3D với ${characters?characters.filter(c=>c>=0).length:4} nhân vật`}>{error&&<div className="webgl-error">Trình duyệt chưa bật 3D. Hãy bật tăng tốc phần cứng hoặc mở bằng Chrome / Edge trên máy tính.</div>}</div>;
}
export default function Home(){const [chosen,setChosen]=useState(0),[started,setStarted]=useState(false),[g,setG]=useState<Game|null>(null),[selected,setSelected]=useState<number[]>([]),[help,setHelp]=useState(false),[sound,setSound]=useState(false),[view,setView]=useState(0);const names=[0,1,2,3].map(i=>people[(chosen+i)%4].name);const audio=useRef<AudioContext|null>(null);
 function beep(){if(!sound)return;try{audio.current??=new AudioContext();void audio.current.resume();const o=audio.current.createOscillator(),v=audio.current.createGain();o.type='sine';o.frequency.value=400;o.connect(v);v.connect(audio.current.destination);v.gain.setValueAtTime(.05,audio.current.currentTime);v.gain.exponentialRampToValueAtTime(.001,audio.current.currentTime+.18);o.start();o.stop(audio.current.currentTime+.2);}catch{}}
 function begin(){setG(fresh());setSelected([]);setStarted(true);beep();}
 useEffect(()=>{if(!g||g.phase!=='play'||g.turn===0)return;const timer=setTimeout(()=>{setG(old=>{if(!old||old.phase!=='play'||old.turn===0)return old;const who=old.turn;if(old.last&&(old.hands[who].length===0||old.hands[old.last.who].length===0||Math.random()<.3))return challenge(old,who,names);const hand=old.hands[who];const honest=hand.map((c,i)=>c===old.target||c==='★'?i:-1).filter(i=>i>=0);const ids=honest.length&&Math.random()<.75?honest.slice(0,Math.ceil(Math.random()*2)):[0];return playCards(old,ids,names);});},1600);return()=>clearTimeout(timer);},[g,chosen]);
 function hit(){if(!g||g.turn!==0||g.phase!=='play'||!selected.length)return;setG(playCards(g,selected,names));setSelected([]);beep();}function call(){if(!g||g.turn!==0||g.phase!=='play'||!g.last)return;setG(challenge(g,0,names));setSelected([]);beep();}function nextRound(){if(!g)return;const next=g.lives[g.loser]>0?g.loser:g.lives.findIndex(n=>n>0);setG({...g,hands:deal(),last:null,target:['K','Q','A'][Math.floor(Math.random()*3)] as Card,turn:next,round:g.round+1,phase:'play',loser:-1,result:'',log:[`Vòng ${g.round+1}. ${names[next]} đi trước.`,...g.log].slice(0,8)});setSelected([]);}
 const gameRef=useRef({g,started,chosen});gameRef.current={g,started,chosen};
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>|void}}).modelContext;if(!ctx)return;const lifecycle=new AbortController();const register=(tool:unknown)=>{try{void Promise.resolve(ctx.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};register({name:'read_office_bluff_state',description:'Read public table state and your own cards. Opponent cards stay hidden.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>{const {g,chosen,started}=gameRef.current;return {started,character:people[chosen].name,round:g?.round,turn:g?.turn,target:g?.target,hand:g?.hands[0],lives:g?.lives,phase:g?.phase};}});register({name:'start_office_bluff_game',description:'Start or restart a local game against three bots with the selected sample character.',inputSchema:{type:'object',properties:{character:{type:'integer',minimum:0,maximum:3}},required:['character'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const c=(input as {character:number})?.character;if(!Number.isInteger(c)||c<0||c>3)throw new Error('Character must be 0–3');flushSync(()=>{setChosen(c);setG(fresh());setSelected([]);setStarted(true);});return {started:true,character:people[c].name};}});return()=>lifecycle.abort();},[]);
 const yourTurn=g?.turn===0&&g?.phase==='play';
 return <main><header className="topbar"><a className="brand" href="/" aria-label="Office Bluff"><Club size={26}/><span>OFFICE<span className="brand-light"> / BLUFF</span></span></a><div className="room-id"><i/> PHÒNG GIẢI LAO <span>01</span></div><div className="header-actions"><span className="prototype">BẢN THỬ NGHIỆM</span><button className="icon-button" aria-label={sound?'Tắt âm thanh':'Bật âm thanh'} onClick={()=>setSound(!sound)}>{sound?<Volume2 size={19}/>:<VolumeX size={19}/>}</button><button className="icon-button" aria-label="Luật chơi" onClick={()=>setHelp(true)}><HelpCircle size={20}/></button></div></header>
 <div className="game-layout"><section className="stage"><Room chosen={chosen} turn={g?.turn??0} loser={g?.phase==='result'?g.loser:-1} reset={view} accusation={g&&g.phase!=='play'&&g.last?{from:g.turn,to:g.last.who}:undefined} cards={g?{round:g.round,counts:g.hands.map((h,i)=>g.lives[i]>0?h.length:0),last:g.last?{who:g.last.who,count:g.last.cards.length}:null}:undefined}/><div className="stage-grain"/><div className="scene-heading"><div className="eyebrow">HẾT GIỜ LÀM. ĐẾN GIỜ ĐẤU TRÍ.</div><h1>Tan ca, <em>lên bài.</em></h1><p>Mặt quen. Bài úp. Ai đáng tin?</p></div><div className="scene-tools"><button onClick={()=>setView(v=>v+1)}><RotateCcw size={15}/> Góc nhìn gốc</button><span>Kéo để xoay · Cuộn để thu phóng</span></div><div className="table-rule"><span>BÀI CỦA BÀN</span><strong>{g?.target??'K'} <span>♠</span></strong><small>{g?'Mọi lượt đều tuyên bố loại bài này':'Sẵn sàng cho một ván?'}</small></div>
 <div className="seat seat-top"><i style={{background:people[(chosen+2)%4].color}}/>{names[2]} <small>MÁY</small>{started&&<span>{'●'.repeat(g?.lives[2]??3)}</span>}</div><div className="seat seat-left"><i style={{background:people[(chosen+1)%4].color}}/>{names[1]} <small>MÁY</small>{started&&<span>{'●'.repeat(g?.lives[1]??3)}</span>}</div><div className="seat seat-right"><i style={{background:people[(chosen+3)%4].color}}/>{names[3]} <small>MÁY</small>{started&&<span>{'●'.repeat(g?.lives[3]??3)}</span>}</div>
 <div className="stage-bottom"><div className="you-tag"><i style={{background:people[chosen].color}}/><span>{names[0]} <small>BẠN</small></span><span className="coffee">{started?'☕'.repeat(g?.lives[0]??3):'☕ ☕ ☕'}</span></div><div className="scene-note">01 — THE BREAK ROOM</div></div></section>
 <aside className="sidebar">{!started?<><div className="eyebrow gold">GHẾ TRỐNG ĐANG ĐỢI BẠN</div><h2>Hôm nay,<br/>bạn là ai?</h2><p className="muted">Chọn một gương mặt quen.<br/>Giữ một bí mật riêng.</p><div className="character-list">{people.map((p,i)=><button key={p.name} onClick={()=>setChosen(i)} className={`character ${chosen===i?'chosen':''}`} aria-pressed={chosen===i}><span className="avatar" style={{background:p.color+'25',color:p.color}}>{p.name.charAt(0)}</span><span><strong>{p.name}</strong><small>{p.role}</small></span><span className="choose-indicator">{chosen===i?'✓':'+'}</span></button>)}</div><div className="quote">{people[chosen].quote}</div><Button className="start-button" onClick={begin}>Vào bàn chơi <ArrowUpRight size={19}/></Button><div className="demo-note"><i/> Chơi thử cùng 3 máy</div><p className="footnote">Nhân vật mẫu · Chưa có phòng online<br/>Ảnh và tên đồng nghiệp sẽ được thêm sau.</p></>:<><div className="eyebrow gold">VÒNG {String(g?.round).padStart(2,'0')} <span className="live-label">ĐANG CHƠI</span></div><h2>{g?.phase==='end'?'Hết giờ bluff.':g?.phase==='result'?'Lật bài!':yourTurn?'Đến lượt bạn.':`${names[g?.turn??0]} đang nghĩ…`}</h2><p className="muted">{g?.phase==='play'?(g.last?`${names[g.last.who]} vừa đánh ${g.last.cards.length} lá ${g.target}. Tin được không?`:`Bàn ${g?.target}: chọn 1–3 lá để đánh úp.`):g?.result}</p>
 {g?.phase==='play'?<><div className="hand-label">BÀI TRÊN TAY <span>{g.hands[0].length} LÁ</span></div><div className="hand animated-hand" key={g.round}>{g.hands[0].map((c,i)=><button key={`${g.round}-${i}`} style={{'--card-index':i,'--card-angle':`${(i-(g.hands[0].length-1)/2)*5}deg`} as React.CSSProperties} aria-label={`Lá ${c}, ${selected.includes(i)?'đã chọn':'chưa chọn'}`} aria-pressed={selected.includes(i)} disabled={!yourTurn} className={`card ${selected.includes(i)?'selected':''} ${c==='★'?'joker':''}`} onClick={()=>setSelected(s=>s.includes(i)?s.filter(j=>j!==i):s.length<3?[...s,i]:s)}><span>{c}</span><b>{c==='★'?'✦':'♠'}</b><small>{c}</small></button>)}</div><p className="hand-hint">★ thay cho mọi loại bài. Có thể đánh bài khác để bluff.</p><Button className="start-button" disabled={!yourTurn||!selected.length} onClick={hit}>Đánh {selected.length||''} lá · Tuyên bố {g.target}<ChevronRight size={18}/></Button><button className="liar-button" onClick={call} disabled={!yourTurn||!g.last}>NÓI DỐI! <span>Lật bài người vừa đánh</span></button>{yourTurn&&g.last&&g.hands[g.last.who].length===0&&<p className="hand-hint">Người trước đã hết bài. Bạn vẫn có thể tố hoặc đánh tiếp.</p>}</>:<><div className="verdict"><span>{g?.phase==='end'?'✦':'☕'}</span><strong>{g?.phase==='end'?`${names[g.winner]} thắng!`:`${names[g?.loser??0]} mời cà phê`}</strong><p>{g?.phase==='end'?'Người cuối cùng còn cà phê trên bàn.':'Hết 3 cà phê sẽ rời ván chơi.'}</p></div><Button className="start-button" onClick={g?.phase==='end'?begin:nextRound}>{g?.phase==='end'?'Chơi ván mới':'Vòng tiếp theo'}<ArrowUpRight size={18}/></Button></>}
 <div className="activity"><div className="hand-label">CHUYỆN TRÊN BÀN</div><div aria-live="polite">{g?.log.slice(0,4).map((l,i)=><p key={i} className={i===0?'latest':''}><span>·</span>{l}</p>)}</div></div><button className="back-button" onClick={()=>{setStarted(false);setG(null);setSelected([]);}}>Rời bàn · Chọn lại nhân vật</button></>}</aside></div>
 <footer><span><i/> MỘT CUỘC VUI SAU GIỜ LÀM</span><button onClick={()=>setHelp(true)}>Luật chơi <ArrowUpRight size={14}/></button><span>ĐỪNG TIN ĐỒNG NGHIỆP QUÁ SỚM.</span></footer>
 <Dialog open={help} onOpenChange={setHelp}><DialogContent className="rules-dialog"><DialogTitle>Luật của phòng giải lao</DialogTitle><DialogDescription>Bản chơi thử rút gọn, lấy cảm hứng từ trò đấu trí bằng bài úp.</DialogDescription><ol><li>Mỗi người có 5 lá bài và 3 cà phê. Mỗi vòng chọn ngẫu nhiên bài K, Q hoặc A.</li><li>Đến lượt, chọn 1–3 lá. Dù đánh gì, bạn luôn tuyên bố đó là bài của bàn. ★ là lá hợp lệ cho mọi bàn.</li><li>Thay vì đánh, bạn có thể hô “Nói dối!” để lật lượt vừa đánh. Người nói dối mất 1 cà phê; nếu họ nói thật, người tố mất 1.</li><li>Sau khi tố, chia lại bài. Hết cà phê thì bị loại; người cuối cùng còn cà phê thắng. Máy tự chơi tiếp nếu bạn bị loại.</li></ol><p>Đây là bản chơi với máy trên thiết bị của bạn. Chưa hỗ trợ nhiều người online.</p><Button onClick={()=>setHelp(false)} className="start-button">Đã hiểu, lên bài!</Button></DialogContent></Dialog></main>;
}
