import test from 'node:test';import assert from 'node:assert/strict';
import {create,join,view,act,rooms,sweep,auth,leave,tick} from './game.mjs';
import {prepareShot,advancePaint} from '../shared/paint.mjs';
import {server} from './index.mjs';
test('Room rules, private hands, valid actions and stale revisions',()=>{rooms.clear();const {room:r,player:a}=create('A',0);const b=join(r.code,'B',1).player;assert.throws(()=>act(r,b,'start',r.revision),/chủ phòng/);act(r,a,'start',r.revision);const va=view(r,a),vb=view(r,b);assert.equal(va.game.hand.length,5);assert.equal(vb.game.hand.length,5);assert.equal(JSON.stringify(va).includes('token'),false);assert.equal(JSON.stringify(va).includes('hands'),false);assert.throws(()=>act(r,b,'play',r.revision,[0]),/lượt/);assert.throws(()=>act(r,a,'play',r.revision,[0,0]),/hợp lệ/);assert.throws(()=>act(r,a,'play',r.revision,[99]),/hợp lệ/);const rev=r.revision;act(r,a,'play',rev,[0]);assert.equal(view(r,b).game.last.count,1);assert.equal(view(r,b).game.last.cards,undefined);assert.throws(()=>act(r,b,'challenge',rev),/thay đổi/);act(r,b,'challenge',r.revision);assert.equal(r.game.lives.reduce((a,b)=>a+b),2);assert.equal(r.game.phase,'loading');assert.equal(r.game.shot.hit,null);assert.throws(()=>act(r,a,'next',r.revision),/chuyển vòng/);assert.throws(()=>act(r,b,'play',r.revision,[0]),/lượt/);assert.throws(()=>join(r.code,'C',2),/bắt đầu/);assert.equal(auth(r.code,a.token).player,a);assert.throws(()=>auth(r.code,'fake'),/hết hạn/);});
test('100 multiplayer matches terminate with one winner',()=>{for(let j=0;j<100;j++){rooms.clear();const {room:r,player:a}=create('A',0);for(let i=1;i<4;i++)join(r.code,'P'+i,i);act(r,a,'start',r.revision);let steps=0;while(r.game.phase!=='end'&&steps++<5000){const g=r.game;if(['loading','firing'].includes(g.phase)){tick(g.shot.resolveAt);continue;}if(g.phase==='result'){tick(r.game.nextRoundAt);continue;}const p=r.players[g.turn];assert(g.lives[g.turn]>0);if(g.last&&(g.hands[g.last.who].length===0||g.hands[g.turn].length===0||Math.random()<.5)){assert.notEqual(g.last.who,g.turn);act(r,p,'challenge',r.revision);}else act(r,p,'play',r.revision,[0]);}assert.equal(r.game.phase,'end');assert.equal(r.game.lives.filter(x=>x>0).length,1);}});
test('Disconnect grace, host transfer, room capacity and isolation',()=>{rooms.clear();const {room:r,player:a}=create('A',0);const b=join(r.code,'B',1).player;join(r.code,'C',2);join(r.code,'D',3);assert.throws(()=>join(r.code,'E',0),/đủ/);const other=create('Z',0);assert.throws(()=>auth(other.room.code,a.token),/hết hạn/);a.lastSeen=Date.now()-91000;sweep();assert.equal(r.host,b.id);assert.equal(r.players.length,3);act(r,b,'start',r.revision);leave(r,b);assert.equal(r.players.find(x=>x.id===b.id).left,true);assert.equal(r.game.phase,'play');assert.notEqual(r.host,b.id);});
test('HTTP clients create, join, start, play, challenge and reconnect',async()=>{rooms.clear();await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;try{const post=async(path,data,token)=>{const r=await fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify(data)});return {status:r.status,data:await r.json()};};const a=(await post('/api/create',{name:'Alice',character:0})).data;const code=a.state.code;const b=(await post('/api/join',{name:'Bob',character:1,code})).data;let s=(await post('/api/action?code='+code,{action:'start',revision:b.state.revision},a.token)).data;assert.equal(s.game.hand.length,5);const bad=await post('/api/action?code='+code,{action:'play',revision:s.revision,indices:[0]},b.token);assert.equal(bad.status,400);s=(await post('/api/action?code='+code,{action:'play',revision:s.revision,indices:[0]},a.token)).data;assert.equal(s.game.hand.length,4);s=(await post('/api/action?code='+code,{action:'challenge',revision:s.revision},b.token)).data;assert.equal(s.game.phase,'loading');assert.equal(s.game.shot.hit,null);const reconnected=await fetch(base+'/api/state?code='+code,{headers:{Authorization:`Bearer ${a.token}`}}).then(r=>r.json());assert.equal(reconnected.you,a.state.you);assert.equal(reconnected.game.hands,undefined);assert.equal((await post('/api/action?code='+code,{action:'next',revision:s.revision},'invalid')).status,400);}finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}});

test('Cocking deadlines, six slots, wrong accusation and single resolution',()=>{
 const base={last:{who:0,cards:['Q']},target:'K',lives:[1,1,1,1],ranks:[null,null,null,null],painted:[false,false,false,false],log:[]};const names=['A','B','C','D'];
 const shot=prepareShot(base,1,names,1000);assert.equal(shot.shot.shooter,1);assert.equal(shot.shot.target,0);
 assert.equal(advancePaint(shot,names,4999,()=>{throw Error('too early')}),shot);
 assert.equal(advancePaint(shot,names,5000).phase,'firing');let hits=0;
 for(let slot=0;slot<6;slot++){const end=advancePaint(shot,names,5700,()=>slot);if(end.shot.hit)hits++;assert.equal(end.lives[0],slot===0?0:1);assert.equal(end.ranks[0],slot===0?4:null);assert.equal(advancePaint(end,names,9000),end);}
 assert.equal(hits,1);const truthful=prepareShot({...base,last:{who:0,cards:['K','★']}},1,names,0);assert.equal(truthful.shot.target,1);assert.equal(truthful.shot.shooter,0);
});
test('Ranks persist, all four placements are unique, leaving cancels pending shot',()=>{
 rooms.clear();const {room:r,player:a}=create('A',0);for(let i=1;i<4;i++)join(r.code,'P'+i,i);act(r,a,'start',r.revision);
 for(let i=0;i<3;i++){r.game.last={who:i,cards:['Q']};r.game.target='K';r.game=prepareShot(r.game,3,r.players.map(p=>p.name),0);r.game=advancePaint(r.game,r.players.map(p=>p.name),4700,()=>0);if(i<2)tick(r.game.nextRoundAt);}
 assert.deepEqual(r.game.ranks,[4,3,2,1]);assert.equal(r.game.phase,'end');
 act(r,a,'start',r.revision);assert.deepEqual(r.game.ranks,[null,null,null,null]);r.game.last={who:0,cards:['Q']};r.game=prepareShot(r.game,1,r.players.map(p=>p.name));leave(r,r.players[1]);assert.equal(r.game.shot,null);const snapshot=JSON.stringify(r.game);tick(Date.now()+9999);assert.equal(JSON.stringify(r.game),snapshot);
});

test('Five blanks consume ammo, sixth shot hits, automatic round preserves ammo',()=>{
 rooms.clear();const {room:r}=create('A',0);const b=join(r.code,'B',1).player;act(r,r.players[0],'start',r.revision);
 for(let k=0;k<6;k++){const oldRound=r.game.round;r.game.last={who:0,cards:['Q']};r.game.target='K';r.game=prepareShot(r.game,1,['A','B'],1000);assert.equal(r.game.shot.remainingBefore,6-k);r.game=advancePaint(r.game,['A','B'],5700,n=>{assert.equal(n,6-k);return n-1});assert.equal(r.game.ammo[0],5-k);assert.equal(r.game.ammo[1],6);if(k<5){assert.equal(r.game.lives[0],1);tick(7699);assert.equal(r.game.phase,'result');tick(7700);assert.equal(r.game.phase,'play');assert.equal(r.game.round,oldRound+1);assert.equal(r.game.ammo[0],5-k);assert.equal(r.game.hands[0].length,5);}else{assert.equal(r.game.phase,'end');assert.equal(r.game.winner,1);tick(99000);assert.equal(r.game.round,oldRound);assert.deepEqual(r.game.ranks,[2,1]);}}
});

test('Last cards force verification, reject play without mutation and handle truth/bluff',()=>{
 for(const card of ['K','Q']){rooms.clear();const {room:r,player:a}=create('A',0);const b=join(r.code,'B',1).player;act(r,a,'start',r.revision);r.game.target='K';r.game.hands[0]=[card];act(r,a,'play',r.revision,[0]);assert.equal(r.game.turn,1);assert.equal(view(r,b).game.counts[0],0);const before=JSON.stringify(r);assert.throws(()=>act(r,b,'play',r.revision,[0]),/kiểm chứng/);assert.equal(JSON.stringify(r),before);act(r,b,'challenge',r.revision);assert.equal(r.game.phase,'loading');assert.equal(r.game.shot.target,card==='K'?1:0);r.game=advancePaint(r.game,['A','B'],r.game.shot.resolveAt,()=>1);tick(r.game.nextRoundAt);assert.equal(r.game.phase,'play');assert.equal(r.game.last,null);act(r,r.players[r.game.turn],'play',r.revision,[0]);}
});
