import {randomInt,randomBytes} from 'node:crypto';
export const rooms=new Map();
const fail=(message)=>{throw new Error(message)};
export function identity(name,character){if(typeof name!=='string'||!name.trim()||name.trim().length>24)fail('Tên phải có 1–24 ký tự.');if(!Number.isInteger(character)||character<0||character>3)fail('Nhân vật không hợp lệ.');return {id:randomBytes(12).toString('hex'),token:randomBytes(32).toString('hex'),name:name.trim(),character,lastSeen:Date.now(),left:false};}
export function create(name,character){if(rooms.size>=100)fail('Máy chủ đầy, hãy thử lại sau.');let code;do{code=Array.from({length:6},()=> 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[randomInt(32)]).join('')}while(rooms.has(code));const p=identity(name,character);const r={code,players:[p],host:p.id,revision:0,game:null,updated:Date.now()};rooms.set(code,r);return {room:r,player:p};}
export function join(code,name,character){const r=rooms.get(code);if(!r)fail('Không tìm thấy phòng.');if(r.game)fail('Ván đã bắt đầu, hãy đợi chủ phòng tạo phòng mới.');if(r.players.length>=4)fail('Phòng đã đủ 4 người.');const p=identity(name,character);r.players.push(p);touch(r);return {room:r,player:p};}
export function touch(r){r.revision++;r.updated=Date.now();}
export function auth(code,token){const r=rooms.get(code);const p=r?.players.find(p=>p.token===token&&!p.left);if(!p)fail('Phiên chơi hết hạn. Hãy vào phòng lại.');p.lastSeen=Date.now();return {room:r,player:p};}
function deal(n){const d=[...Array(6).fill('K'),...Array(6).fill('Q'),...Array(6).fill('A'),'★','★'];for(let i=d.length-1;i>0;i--){const j=randomInt(i+1);[d[i],d[j]]=[d[j],d[i]];}return Array.from({length:n},(_,i)=>d.slice(i*5,i*5+5));}
function round(r,turn=0){const g=r.game;const lives=g?.lives??r.players.map(p=>p.left?0:3);const first=lives[turn]>0?turn:lives.findIndex(x=>x>0);r.game={hands:deal(r.players.length),lives,turn:first,round:(g?.round??0)+1,target:['K','Q','A'][randomInt(3)],last:null,phase:'play',winner:-1,loser:-1,result:'',log:[`Vòng ${(g?.round??0)+1}. ${r.players[first].name} đi trước.`]};}
export function view(r,p){const g=r.game;return {code:r.code,revision:r.revision,host:r.host,you:p.id,players:r.players.map(x=>({id:x.id,name:x.name,character:x.character,connected:!x.left&&Date.now()-x.lastSeen<20000,left:x.left})),game:g?{...g,hands:undefined,hand:g.hands[r.players.indexOf(p)],counts:g.hands.map(h=>h.length),last:g.last?{who:g.last.who,count:g.last.cards.length}:null}:null};}
function log(g,s){g.log=[s,...g.log].slice(0,8)}
export function act(r,p,action,revision,indices){if(revision!==r.revision)fail('Trạng thái vừa thay đổi. Hãy thử lại.');const i=r.players.indexOf(p);let g=r.game;
 if(action==='start'){if(r.host!==p.id)fail('Chỉ chủ phòng được bắt đầu.');if(g&&g.phase!=='end')fail('Ván đang diễn ra.');if(r.players.filter(x=>!x.left&&Date.now()-x.lastSeen<20000).length<2)fail('Cần ít nhất 2 người đang kết nối.');if(r.players.some(x=>!x.left&&Date.now()-x.lastSeen>=20000))fail('Đợi mọi người kết nối lại hoặc rời phòng.');if(g){r.players=r.players.filter(x=>!x.left);r.game=null;}round(r);touch(r);return;}
 if(!g)fail('Ván chưa bắt đầu.');if(action==='next'){if(r.host!==p.id)fail('Chỉ chủ phòng chuyển vòng.');if(g.phase!=='result')fail('Chưa thể chuyển vòng.');round(r,g.loser);touch(r);return;}
 if(g.phase!=='play'||g.turn!==i||g.lives[i]<=0)fail('Chưa đến lượt bạn.');
 if(action==='play'){if(!Array.isArray(indices)||indices.length<1||indices.length>3||new Set(indices).size!==indices.length||indices.some(n=>!Number.isInteger(n)||n<0||n>=g.hands[i].length))fail('Chọn 1–3 lá hợp lệ.');const cards=indices.map(j=>g.hands[i][j]);g.hands[i]=g.hands[i].filter((_,j)=>!indices.includes(j));g.last={who:i,cards};log(g,`${p.name} đánh ${cards.length} lá ${g.target}.`);let next=-1;for(let n=1;n<r.players.length;n++){const k=(i+n)%r.players.length;if(g.lives[k]>0&&g.hands[k].length){next=k;break;}}if(next<0){for(let n=1;n<r.players.length;n++){const k=(i+n)%r.players.length;if(g.lives[k]>0){next=k;break;}}}g.turn=next;
 }else if(action==='challenge'){if(!g.last||g.last.who===i)fail('Chưa có lượt để tố.');const lied=g.last.cards.some(c=>c!==g.target&&c!=='★');g.loser=lied?g.last.who:i;g.lives[g.loser]--;g.result=`${r.players[g.last.who].name} ${lied?'nói dối':'nói thật'}! Bài lật: ${g.last.cards.join(' · ')}. ${r.players[g.loser].name} mất 1 cà phê.`;log(g,g.result);const alive=g.lives.map((v,i)=>v>0?i:-1).filter(i=>i>=0);g.phase=alive.length===1?'end':'result';g.winner=alive.length===1?alive[0]:-1;
 }else fail('Hành động không hợp lệ.');touch(r);
}
export function leave(r,p){if(p.left)return;p.left=true;const g=r.game;if(g){const i=r.players.indexOf(p);g.lives[i]=0;const alive=g.lives.map((v,i)=>v>0?i:-1).filter(i=>i>=0);if(alive.length<=1){g.phase='end';g.winner=alive[0]??-1;g.result=`${p.name} rời bàn.`;}else{round(r,alive[0]);r.game.log.unshift(`${p.name} rời bàn. Chia lại bài.`);}}else r.players=r.players.filter(x=>x!==p);if(r.host===p.id)r.host=r.players.find(x=>!x.left)?.id??'';if(r.players.every(x=>x.left))rooms.delete(r.code);touch(r);}
export function sweep(now=Date.now()){for(const r of rooms.values()){for(const p of [...r.players])if(!p.left&&now-p.lastSeen>90000)leave(r,p);if(now-r.updated>7200000)rooms.delete(r.code);}}
